admin:
  port: 9990
  ip: 0.0.0.0

routers:
- protocol: http
  label: rahgot
  dtab: /svc => /$/inet/rahgot/5000;
  servers:
  - port: 3001
    ip: 0.0.0.0
- protocol: http
  label: krosis
  dtab: /svc => /$/inet/krosis/5000;
  servers:
  - port: 5001
    ip: 0.0.0.0
- protocol: http
  label: vokun
  dtab: /svc => /$/inet/vokun/5000;
  servers:
  - port: 7001
    ip: 0.0.0.0