version: "3"
services:
  krosis:
    build: krosis/
    ports: 
      - "5000:5000"
    volumes:
      - ./krosis:/code
  rahgot:
    build: rahgot/
    ports: 
      - "3000:5000"
    volumes:
      - ./rahgot:/code
  vokun:
    build: vokun/
    ports:
      - "7000:5000"
    volumes:
      - ./vokun:/code
  redis:
    image: "redis:alpine"
  linkerd:
    image: "buoyantio/linkerd:latest"
    command:
      - /config.yaml
    ports:
      - "9990:9990"
      - "3001:3001"
      - "5001:5001"
      - "7001:7001"
    volumes:
      - ./config.yaml:/config.yaml
