version: "3"
services:
  krosis:
    build: krosis/
    ports: 
      - "5000:5000"
    volumes:
      - ./krosis:/code
  bar:
    build: bar/
    ports: 
      - "3000:5000"
    volumes:
      - ./bar:/code
  baz:
    build: baz/
    ports:
      - "7000:5000"
    volumes:
      - ./baz:/code
  redis:
    image: "redis:alpine"
  linkerd:
    image: "buoyantio/linkerd:latest"
    command:
      - /config.yaml
    ports:
      - "9990:9990"
      - "3001:3001"
      - "5001:5001"
      - "7001:7001"
    volumes:
      - ./config.yaml:/config.yaml
