version: "3"
services:
  krosis:
    container_name: krosis
    build: krosis/
    volumes:
      - ./krosis:/code
  rahgot:
    container_name: rahgot
    build: rahgot/
    volumes:
      - ./rahgot:/code
  nahkriin:
    container_name: nahkriin
    build: nahkriin/
    volumes:
      - ./nahkriin:/code
  vokun:
    container_name: vokun
    build: vokun/
    ports:
      - 5000:5000
    volumes:
      - ./vokun:/code
  redis:
    container_name: redis
    image: "redis:alpine"